name: Terraform Apply

on:
  push: 
    branches:
      - main
      

jobs:
  apply-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"
          terraform_wrapper: true

      - name: Terraform Init
        id: init
        run: terraform init


      - name: Run Terraform Apply
        id: plan
        run: terraform apply -auto-approve -var-file=tfvars/production.tfvars 